Dv routing
elegantamvc/eleganta pull request #4
Opened 2017-01-27 04:36 UTC by Kiricon

Changes:
1) Added `match` method for general routing.
2) Added 404 page and routing (not styled yet)
3) Added 500 error page with in depth stack tracing and and integrated editor (File is large, open with sublime, inlining the ace editor really messed it up)
4) Renaming routing files, but honestly I don't know how to make the names much better :(

I will continue working in this branch and making the changes we had last spoken of for the router.

2017-01-27 14:55 UTC, ava-cassiopeia requested changes
See my comments. Totally open to discussion on those. Otherwise code looks good.

2017-01-27 14:55 UTC, aeolingamenfel commented on core.js
> +        require(currentPath + '/' + Config.routesFolder + '/routes.js')
Is there a particular reason why we're calling it `Config` instead of `config`?

2017-01-27 14:55 UTC, aeolingamenfel commented on core/route/allrouting.js
> +            this[method.toLowerCase()](path, controllerAction);
I would maybe have a constant array in this class something like

```
const allowedMethod = ["get", "post", "patch", "put"];
```

And run `method.toLowerCase()` through that first, just so people know when they typed something wrong.

2017-01-27 15:09 UTC, Kiricon commented on core.js
> +        require(currentPath + '/' + Config.routesFolder + '/routes.js')
Nope, I'll just rename it real quick. It is inconsistent.

2017-01-27 15:10 UTC, aeolingamenfel commented on core.js
> +        require(currentPath + '/' + Config.routesFolder + '/routes.js')
Awesome, thanks.

2017-01-27 15:10 UTC, Kiricon commented on core/route/allrouting.js
> +            this[method.toLowerCase()](path, controllerAction);
I had thought about that but had overlooked it at the time due to us not having a consistent means for returning errors. Regardless we will need it in the end so I'll add that fix real quick.

2017-01-27 15:11 UTC, aeolingamenfel commented on core/route/allrouting.js
> +            this[method.toLowerCase()](path, controllerAction);
Yeah, true. For now I'd just say make a class that extends `Error` like `IllegalMethodError` and just throw that. We can do more with catching that later.

2017-01-27 15:14 UTC, Kiricon commented on core/route/allrouting.js
> +            this[method.toLowerCase()](path, controllerAction);
I was planning on making error handling a full task for the future. Good errors handling is a big help.

2017-01-27 15:15 UTC, aeolingamenfel commented on core/route/allrouting.js
> +            this[method.toLowerCase()](path, controllerAction);
Agreed 100%.

2017-01-29 00:31 UTC, ava-cassiopeia approved these changes
👍

2017-01-29 00:33 UTC, merged